spring:
  application:
    name: ferreteria
  datasource:
    url: jdbc:mysql://localhost:3306/db_ferreteria
    username: root
    password: alumnos
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
